name: Send twitter messages

on:
  schedule:
    # UTC Timezone. Should be verified
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  sent_tweets:
    name: Send tweets
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
          cache: true
      - run: go version
      - run: go run main.go
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          BREEZOMETER_TOKEN: ${{ secrets.BREEZOMETER_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
